default: &default
  adapter: postgresql
  pool: 5
  port: 5432
  username: <%= ENV['RAILS-COOK_DATABASE_USERNAME'] %>
  password: <%= ENV['RAILS-COOK_DATABASE_PASSWORD'] %>
  encoding: utf8

development:
  <<: *default
  database: rails-cook

test:
  <<: *default
  database: rails-cook-test

production:
  <<: *default
  database: rails-cook
