development:
  secret_key_base: 4d7cf2bf6ffe0a8950335334b38be3940aa9fe2ae3876a909ef22d788b6818c16dff00d9a80096139dda1bbc105f7459cc0bf468b0924909190b55d26b5dbe9a
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  vkontakte_app_id: <%= ENV["VK_APP_ID"] %>
  vkontakte_app_secret: <%= ENV["VK_APP_SECRET"] %>
  github_app_id: <%= ENV["GITHUB_APP_ID"] %>
  github_app_secret: <%= ENV["GITHUB_APP_SECRET"] %>

test:
  secret_key_base: a6aa1ab55ac4e51e16540cb2fe363c0d92d54c307de11f92d844665dfd7d42f72a3689ce423596d6d00a7f1f560cb7e46798b2f27d1d6d81fd34ea0b12b2dabc

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
