if Category.count == 0
	Category.create name: 'snacks', caption: 'Закуски'
	Category.create name: 'salads', caption: 'Салаты'
	Category.create name: 'soups', caption: 'Супы'
	Category.create name: 'hots', caption: 'Основное'
	Category.create name: 'porridges', caption: 'Каши'
	Category.create name: 'desserts', caption: 'Десерты'
	Category.create name: 'pastries', caption: 'Выпечка'
	Category.create name: 'sauces', caption: 'Соусы'
	Category.create name: 'drinks', caption: 'Напитки'
	Category.create name: 'dough', caption: 'Тесто'
	Category.create name: 'jam', caption: 'Заготовки'
end

if Country.count == 0
	Country.create name: 'russian', caption: 'Русская'
	Country.create name: 'spanish', caption: 'Испанская'
	Country.create name: 'italian', caption: 'Итальянская'
	Country.create name: 'french', caption: 'Французская'
	Country.create name: 'japanese', caption: 'Японская'
	Country.create name: 'ukrainian', caption: 'Украинская'
	Country.create name: 'english', caption: 'Английская'
	Country.create name: 'hellas', caption: 'Греческая'
	Country.create name: 'georgian', caption: 'Грузинская'
	Country.create name: 'indian', caption: 'Индийская'
	Country.create name: 'chinese', caption: 'Китайская'
	Country.create name: 'mexican', caption: 'Мексиканская'
end

if Measure.count == 0
	Measure.create name: 'гр'
	Measure.create name: 'кг'
	Measure.create name: 'мл'
	Measure.create name: 'л'
	Measure.create name: 'шт'
	Measure.create name: 'ч.л'
	Measure.create name: 'ст.л'
	Measure.create name: 'стакан'
	Measure.create name: 'пучок'
	Measure.create name: 'упак.'
	Measure.create name: 'перо'
	Measure.create name: 'ветка'
	Measure.create name: 'черешок'
end

Ingridient.all.each do |ing|
	ing.destroy
end

Ingridient.create name: 'Абрикос'
Ingridient.create name: 'Айва'
Ingridient.create name: 'Алыча'
Ingridient.create name: 'Ананас'
Ingridient.create name: 'Апельсин'
Ingridient.create name: 'Арбуз'
Ingridient.create name: 'Банан'
Ingridient.create name: 'Брусника'
Ingridient.create name: 'Виноград'
Ingridient.create name: 'Вишня'
Ingridient.create name: 'Груша'
Ingridient.create name: 'Дыня'
Ingridient.create name: 'Земляника'
Ingridient.create name: 'Калина'
Ingridient.create name: 'Клубника'
Ingridient.create name: 'Крыжовник'
Ingridient.create name: 'Лимон'
Ingridient.create name: 'Малина'
Ingridient.create name: 'Мандарин'
Ingridient.create name: 'Мирабель'
Ingridient.create name: 'Персик'
Ingridient.create name: 'Слива'
Ingridient.create name: 'Смородина красная'
Ingridient.create name: 'Смородина черная'
Ingridient.create name: 'Ткемали'
Ingridient.create name: 'Черешня'
Ingridient.create name: 'Черника'
Ingridient.create name: 'Яблоко'